# Generated by Django 4.0.8 on 2026-07-02 03:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Tên lớp')),
            ],
            options={
                'verbose_name': 'Lớp học',
                'verbose_name_plural': 'Lớp học',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Tên môn học')),
            ],
            options={
                'verbose_name': 'Môn học',
                'verbose_name_plural': 'Môn học',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên giảng viên')),
                ('classes', models.ManyToManyField(blank=True, related_name='teachers', to='lms_manager.classroom', verbose_name='Lớp giảng dạy')),
                ('subjects', models.ManyToManyField(related_name='teachers', to='lms_manager.subject', verbose_name='Môn giảng dạy')),
            ],
            options={
                'verbose_name': 'Giảng viên',
                'verbose_name_plural': 'Giảng viên',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Tên học sinh')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lms_manager.classroom', verbose_name='Lớp')),
            ],
            options={
                'verbose_name': 'Học sinh',
                'verbose_name_plural': 'Học sinh',
            },
        ),
        migrations.CreateModel(
            name='PaymentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên đợt đóng tiền')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_periods', to='lms_manager.classroom', verbose_name='Lớp học')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_periods', to='lms_manager.subject', verbose_name='Môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_periods', to='lms_manager.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Đợt đóng tiền',
                'verbose_name_plural': 'Đợt đóng tiền',
                'ordering': ['classroom__name', 'subject__name', 'name'],
                'unique_together': {('name', 'classroom', 'teacher', 'subject')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền đóng')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày đóng')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms_manager.classroom', verbose_name='Lớp')),
                ('payment_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms_manager.paymentperiod', verbose_name='Đợt đóng tiền')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms_manager.student', verbose_name='Học sinh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms_manager.subject', verbose_name='Môn học')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='lms_manager.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Thanh toán học phí',
                'verbose_name_plural': 'Thanh toán học phí',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_manager.student', verbose_name='Học sinh')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_manager.subject', verbose_name='Môn đăng ký')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='lms_manager.teacher', verbose_name='Giáo viên hướng dẫn')),
            ],
            options={
                'verbose_name': 'Đăng ký học',
                'verbose_name_plural': 'Đăng ký học',
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
