# Generated by Django 4.0.8 on 2026-07-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_pdf',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Biên lai PDF'),
        ),
    ]
