# Generated by Django 4.0.8 on 2026-07-06 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0002_payment_receipt_pdf'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentperiod',
            options={'ordering': ['subject__name', 'name'], 'verbose_name': 'Đợt đóng tiền', 'verbose_name_plural': 'Đợt đóng tiền'},
        ),
        migrations.AlterUniqueTogether(
            name='paymentperiod',
            unique_together={('name', 'teacher', 'subject')},
        ),
        migrations.RemoveField(
            model_name='paymentperiod',
            name='classroom',
        ),
    ]
