# Generated by Django 4.0.8 on 2026-07-12 09:18

from django.db import migrations, models

def migrate_payment_status(apps, schema_editor):
    Student = apps.get_model('lms_manager', 'Student')
    Payment = apps.get_model('lms_manager', 'Payment')
    
    for payment in Payment.objects.all().select_related('payment_period', 'student'):
        if not payment.student:
            continue
        
        period_name = payment.payment_period.name.lower()
        period_num = None
        for i in range(1, 9):
            if f"đợt {i}" in period_name or f"dot {i}" in period_name or str(i) in period_name:
                period_num = i
                break
        
        if period_num:
            field_name = f"dot_{period_num}"
            setattr(payment.student, field_name, "Đã đóng")
            payment.student.save()

class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0004_student_phone_teacher_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='dot_1',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_2',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_3',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_4',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 4'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_5',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 5'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_6',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 6'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_7',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 7'),
        ),
        migrations.AddField(
            model_name='student',
            name='dot_8',
            field=models.CharField(choices=[('Chưa đóng', 'Chưa đóng'), ('Đã đóng', 'Đã đóng')], default='Chưa đóng', max_length=20, verbose_name='Đợt 8'),
        ),
        migrations.RunPython(migrate_payment_status, reverse_code=migrations.RunPython.noop),
    ]

