# Generated by Django 4.0.8 on 2026-07-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0005_student_dot_1_student_dot_2_student_dot_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tên lớp'),
        ),
    ]
