# Generated by Django 4.0.8 on 2026-07-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0006_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu học'),
        ),
    ]
