# Generated by Django 4.0.8 on 2026-07-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0007_student_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Tên lớp'),
        ),
    ]
