# Generated by Django 4.0.8 on 2026-07-12 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0008_alter_classroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='lms_manager.teacher', verbose_name='Giảng viên'),
        ),
        migrations.AddField(
            model_name='student',
            name='school_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lớp học của học sinh'),
        ),
    ]
