# Generated by Django 4.0.8 on 2026-07-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0009_classroom_teacher_student_school_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classroom',
        ),
        migrations.AddField(
            model_name='student',
            name='classrooms',
            field=models.ManyToManyField(related_name='students', to='lms_manager.classroom', verbose_name='Lớp'),
        ),
    ]
