# Generated by Django 4.0.8 on 2026-07-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0010_remove_student_classroom_student_classrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='classes',
        ),
    ]
