# Generated by Django 4.0.8 on 2026-07-12 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0011_remove_teacher_classes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='student',
            name='classrooms',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.AddField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lms_manager.classroom', verbose_name='Lớp'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='lms_manager.classroom', verbose_name='Lớp giảng dạy'),
        ),
    ]
