# Generated by Django 4.1 on 2026-07-19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0012_remove_classroom_teacher_remove_student_classrooms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày thu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='receipts/batches/', verbose_name='Biên lai tổng hợp PDF')),
                ('payments', models.ManyToManyField(related_name='batches', to='lms_manager.payment')),
            ],
            options={
                'verbose_name': 'Phiếu thu tổng hợp',
                'verbose_name_plural': 'Phiếu thu tổng hợp',
                'ordering': ['-created_at'],
            },
        ),
    ]
