# Generated by Django 4.1 on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0014_one_teacher_per_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Doanh thu')),
                ('teacher_share_rate', models.DecimalField(decimal_places=4, default='0.8000', max_digits=5, verbose_name='Tỷ lệ giảng viên nhận')),
                ('teacher_amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền quyết toán cho giảng viên')),
                ('settled_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm quyết toán')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_settlements', to='lms_manager.classroom', verbose_name='Lớp')),
                ('payments', models.ManyToManyField(related_name='teacher_settlements', to='lms_manager.payment', verbose_name='Các khoản học phí')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='lms_manager.teacher', verbose_name='Giảng viên')),
            ],
            options={
                'verbose_name': 'Quyết toán giảng viên',
                'verbose_name_plural': 'Quyết toán giảng viên',
                'ordering': ['-settled_at'],
            },
        ),
    ]
