# Generated by Django 4.1 on 2026-07-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_manager', '0015_teachersettlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(
                choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản')],
                default='cash',
                max_length=20,
                verbose_name='Hình thức thanh toán',
            ),
        ),
    ]
