# Generated by Django 4.0.8 on 2026-09-30 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms_manager', '0018_remove_student_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, verbose_name='Tên học sinh')),
                ('classroom_name', models.CharField(max_length=150, verbose_name='Lớp học')),
                ('subject_name', models.CharField(max_length=150, verbose_name='Môn học')),
                ('teacher_name', models.CharField(max_length=150, verbose_name='Giảng viên')),
                ('payment_period_name', models.CharField(max_length=100, verbose_name='Đợt thu')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản')], default='bank_transfer', max_length=20, verbose_name='Hình thức thanh toán')),
                ('payer_phone', models.CharField(max_length=30, verbose_name='Số điện thoại')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Mã giao dịch')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('status', models.CharField(choices=[('pending', 'Chờ xác nhận'), ('approved', 'Đã xác nhận'), ('rejected', 'Từ chối')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Thời điểm xác nhận')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Thời điểm gửi')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='lms_manager.payment', verbose_name='Giao dịch được tạo')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_requests', to=settings.AUTH_USER_MODEL, verbose_name='Người xác nhận')),
            ],
            options={
                'verbose_name': 'Yêu cầu thu học phí',
                'verbose_name_plural': 'Yêu cầu thu học phí',
                'ordering': ['-created_at'],
            },
        ),
    ]
