# Generated by Django 4.0.8 on 2026-09-30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("lms_manager", "0020_paymentrequest_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrequest",
            name="request_group",
            field=models.UUIDField(
                db_index=True,
                default=uuid.uuid4,
                editable=False,
                verbose_name="Nhóm yêu cầu",
            ),
        ),
    ]